apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
    spec:
      containers:
      - name: otel
        image: otel/opentelemetry-collector-contrib:0.91.0

        args:
        - "--config=/etc/otel/otel.yaml"

        ports:
        - containerPort: 4317
        - containerPort: 4318

        volumeMounts:
        - name: config
          mountPath: /etc/otel
          readOnly: true

      volumes:
      - name: config
        configMap:
          name: otel-config
