apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-metrics-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-metrics-app
  template:
    metadata:
      labels:
        app: demo-metrics-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter
        ports:
        - containerPort: 9100
