apiVersion: v1
kind: Pod
metadata:
  name: demo-logger
  namespace: default
  labels:
    app: demo-logger
spec:
  containers:
    - name: logger
      image: busybox
      command: ["/bin/sh","-c","while true; do echo 'Hello Loki'; sleep 5; done"]
